# fly.toml app configuration file generated for arty-organizer-redis on 2026-09-16T16:09:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arty-organizer-redis'
primary_region = 'fra'

[build]
  image = 'redis:7-alpine'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
